[content-length]
type = "int64"

[content-md5]
type = "string"

[content-type]
type = "string"

[etag]
type = "string"

[id]
type = "string"
export = true
description = "ID is the unique key in storage."

[last-modified]
type = "time"

[link-target]
type = "string"
description = "LinkTarget is the symlink target for link object."

[max-part-count]
type = "int"
description = "Maximum part number in multipart operation"

[max-part-size]
type = "int64"
description = "Maximum part size defined by storager"

[min-part-size]
type = "int64"
description = "Minimum part size defined by storager"

[mode]
type = "ObjectMode"
export = true

[multipart-id]
type = "string"
description = "MultipartID is the part id of part object."

[path]
type = "string"
export = true
description = "Path is either the absolute path or the relative path towards storage's WorkDir depends on user's input."

[service-metadata]
type = "string_string_map"
description = "ServiceMetadata stores service defined metadata"

[user-metadata]
type = "string_string_map"
description = "UserMetadata stores user defined metadata"