[append-offset]
type = "int64"
description = "AppendOffset is the offset of the append object"

[append-number-maximum]
type = "int"
description = "Max append numbers in append operation"

[append-size-maximum]
type = "int64"
description = "Max append size in per append operation"

[append-total-size-maximum]
type = "int64"
description = "Max append total size in append operation"

[content-length]
type = "int64"

[content-md5]
type = "string"

[content-type]
type = "string"

[etag]
type = "string"

[id]
type = "string"
export = true
description = "ID is the unique key in storage."

[last-modified]
type = "time"

[link-target]
type = "string"
description = "LinkTarget is the symlink target for link object."

[mode]
type = "ObjectMode"
export = true

[multipart-id]
type = "string"
description = "MultipartID is the part id of part object."

[multipart-number-maximum]
type = "int"
description = "Maximum part number in multipart operation"

[multipart-size-maximum]
type = "int64"
description = "Maximum part size defined by storager"

[multipart-size-minimum]
type = "int64"
description = "Minimum part size defined by storager"

[path]
type = "string"
export = true
description = "Path is either the absolute path or the relative path towards storage's WorkDir depends on user's input."

[service-metadata]
type = "any"
description = "ServiceMetadata stores service defined metadata"

[user-metadata]
type = "string_string_map"
description = "UserMetadata stores user defined metadata"