[package]
name = "aos-specs"
version = "0.1.0"
authors = ["Xuanwo <github@xuanwo.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rust-embed = { version = "5.8.0", features = ["compression"] }
toml = "0.5.8"
anyhow = "1.0.38"
lazy_static = "1.4.0"
