name: "Unit Test"

on: [ push,pull_request ]

jobs:
  go_unit_test:
    name: Golang Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ "1.14", "1.15" ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: make go

  rust_unit_test:
    name: Rust Unit Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: make rust
